[tool.pixi.project]
name = "python-bc"
version = "2024.10.26"
readme = "README.md"
license = "CC-BY-NC-SA-4.0"
channels = ["conda-forge"]
platforms = ["linux-64"]
description = ""
authors = [
    "OASCI <us@oasci.org>",
]

[tool.pixi.environments]
dev = ["dev"]

[tool.pixi.dependencies]
python = ">=3.13.0,<4"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.5.42,<10"
jupyterlab = ">=4.2.5,<5"
pymdown-extensions = ">=10.11.2,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocstrings = ">=0.26.2,<0.27"
mkdocstrings-python = ">=1.12.2,<2"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-jupyter = ">=0.25.0,<0.26"
mkdocs-glightbox = ">=0.4.0,<0.5"
matplotlib = ">=3.9.2,<4"
seaborn = ">=0.13.2,<0.14"

[tool.pixi.pypi-dependencies]
material-plausible-plugin = ">=0.2.0,<0.3"
mkdocs-awesome-pages-plugin = ">=2.9.3,<3"
mkdocs-print-site-plugin = ">=2.6.0,<3"

[tool.pixi.feature.dev.dependencies]
black = ">=24.10.0,<25"
isort = ">=5.13.2,<6"
ruff = ">=0.7.1,<0.8"
bump-my-version = ">=0.27.0,<0.28"

[tool.pixi.tasks]
docs = { cmd = ["mkdocs", "build", "-d", "public/", "--clean"] }
docs-cache = { cmd = ["mkdocs", "build", "-d", "public/"] }
serve = { cmd = ["mkdocs", "serve", "-a", "localhost:29847", "--open", "--dirty"] }
